### ISSUE TITLE
Possible memory leak 

### ISSUE THREAD

**Issue by GavinDmello** [mcollina/aedes#51] opened 2016-05-12 15:13 UTC
I surfaced a possible memory leak in aedes while sending 20,000 messages in a one to one setup (one sender,one receiver)

I got the following warning
```
(node) warning: possible EventEmitter memory leak detected. 501 drain listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Socket.addListener (events.js:239:17)
    at Socket.Readable.on (_stream_readable.js:665:33)
    at Socket.once (events.js:265:8)
    at write (/Users/gavindmello/aedes/proxy/src/node_modules/aedes/lib/write.js:9:17)
    at writeQoS (/Users/gavindmello/aedes/proxy/src/node_modules/aedes/lib/client.js:101:5)
    at MemoryPersistence.outgoingUpdate (/Users/gavindmello/aedes/proxy/src/node_modules/aedes/node_modules/aedes-persistence/persistence.js:180:14)
    at Client.deliverQoS (/Users/gavindmello/aedes/proxy/src/node_modules/aedes/lib/client.js:84:26)
    at deliver (/Users/gavindmello/aedes/proxy/src/node_modules/aedes/lib/client.js:134:12)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

I'm think the listener drain in the write.js file isn't removed. The issue however subsided when I added client.conn.removeAllListeners('drain') . Here

```
'use strict'

var mqtt = require('mqtt-packet')

function write (client, packet, done) {
  var result = mqtt.writeToStream(packet, client.conn)

  if (!result && !client.errored && done) {
    client.conn.once('drain', done)
    client.conn.removeAllListeners('drain');
  } else if (done) {

    setImmediate(done)
  }
}

module.exports = write
```
Any sort of assistance would be helpful

**Comment by mcollina** [comment] 2016-05-12 15:20
What are you using to send those messages? I couldn't replicate that behavior myself.

Have you seen an increase in memory?

Your fix will likely create a memory leak, because those callbacks needs to be callled.

**Comment by mcollina** [comment] 2016-05-12 15:29
What are you using to send those messages? I couldn't replicate that behavior myself.

Have you seen an increase in memory?

Your fix will likely create a memory leak, because those callbacks needs to be callled.

**Comment by GavinDmello** [comment] 2016-05-12 15:32
I'm using the standard mqtt client(Mqtt.js) and No significant changes in memory

**Comment by mcollina** [comment] 2016-05-13 07:07
Can you please upload your script, so I can reproduce?

**Comment by GavinDmello** [comment] 2016-05-13 08:22
Here is the link of the sample clients I'm trying to connect with : 

https://gist.github.com/GavinDmello/d614940e0f89383f3f471b90ec121360

**Comment by mcollina** [comment] 2016-05-13 08:24
I will have a look. BTW, a latency tester is a nice OSS project that might benefit the community.
Also, check out https://github.com/mcollina/native-hdr-histogram.

**Comment by mcollina** [comment] 2016-05-22 08:56
@GavinDmello can you please upload the code of your broker? because of this line https://github.com/mcollina/aedes/blob/master/aedes.js#L43 the warning should not appear.
(try increasing that factor, that is the correct way to do it)

**Comment by GavinDmello** [comment] 2016-05-23 14:28
I increased the concurrency factor to 1000 which solved the issue. What should the ideal factor be if I'm expecting a  max concurrency of 50k messages/sec .

**Comment by mcollina** [comment] 2016-05-23 14:36
The value should be dimensioned on how slow your clients are.
This is a bug, in the sense that it should not be shown as a warning, but rather through some events and the like. I'll put some thinking into it.

**Comment by mcollina** [comment] 2016-08-03 06:58
Closing, as I think this was solved. Feel free to reopen.

**Closed by mcollina** 2016-08-03 06:58 UTC

**Comment by cordovapolymer** [comment] 2017-02-24 01:25
Possibly this is the same issue as https://github.com/mcollina/aedes/issues/88
