### ISSUE TITLE
no such packet Error: no such packet, after server restart

### ISSUE THREAD

**Issue by cordovapolymer** [mcollina/aedes#87] opened 2017-02-21 02:26 UTC
https://github.com/mcollina/aedes/issues/83 is a great fix, aedes is much more stable now.

How can such error be fixed for a situation when a client has published a message and server has been restarted that moment, so server doesn't know about the packet, and a client still waits for it?

**Comment by mcollina** [comment] 2017-02-21 07:43
Can you attach a script to reproduce that case?

**Comment by cordovapolymer** [comment] 2017-03-05 01:45
cannot reproduce the issue, still got it in production after update to 0.25.1 . It happened this way, I stopped mosca which was serving multiple clients, and started update aedes which started outputting hundreds of 
` client error e9803d1f no such packet Error: no such packet
    at MemoryPersistence.incomingDelPacket (/home/app/node_modules/aedes-persistence/persistence.js:257:11)
    at ClientPacketStatus.pubrelDel (/home/app/node_modules/aedes/lib/handlers/pubrel.js:47:15)
    at makeCall (/home/app/node_modules/fastseries/series.js:113:10)
    at DestroyableTransform.ResultsHolder.release (/home/app/node_modules/fastseries/series.js:96:9)
    at Object.onceWrapper (events.js:291:19)
    at emitNone (events.js:91:20)
    at DestroyableTransform.emit (events.js:186:7)
    at onwriteDrain (/home/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:370:12)
    at afterWrite (/home/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:358:18)
    at onwrite (/home/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:352:9)
` 
I had to switch my production back to mosca..
@wuhkuh @GavinDmello @mcollina  , any ideas?

**Comment by GavinDmello** [comment] 2017-03-05 09:46
@cordovapolymer Are these clients connected with clean true ?

**Comment by cordovapolymer** [comment] 2017-03-05 13:47
@GavinDmello yes

**Comment by GavinDmello** [comment] 2017-03-05 18:44
@cordovapolymer Could you provide the server & script with basic settings ?
It's very difficult to reproduce otherwise.

**Comment by cordovapolymer** [comment] 2017-03-24 03:30
@GavinDmello , try to reproduce it this way: 
1) start a client1 and client2 both in QOS2 mode from [ @yutter testsuite](https://github.com/mcollina/aedes/issues/88#issue-209456899) together with mosca
2) stop mosca and start aedes
you will see the no such packet error.

**Comment by GavinDmello** [comment] 2017-03-24 06:18
@cordovapolymer Still can't reproduce it.

**Comment by mcollina** [comment] 2017-07-10 10:57
Closing.

**Closed by mcollina** 2017-07-10 10:57 UTC

**Comment by cordovapolymer** [comment] 2017-07-20 13:01
the issue has been resolved, running 0.27 and newer version for more than a week in production

**Comment by gnought** [comment] 2022-08-10 15:02
I guess you are saying to manually ack a client by PUBREC after a aedes restart. May we know
- is Aedes a stand-alone mode?
- what persistence layer do you use?

**Comment by grphine** [comment] 2022-08-15 09:54
I'm not entirely sure how the protocol works. Until now I've been using it as is. I looked around and I think it is the PUBREC as per #137.
Regarding your first question - I'm not entirely certain what you're asking. I did a quick search on the documentation but couldn't find "stand-alone". The aedes object is called without any setting modifications, however.
The QoS of the client is currently at 2.
